-- =========================================================
-- VendingMiniMarket
-- HU-18: Relaciones de abastecimiento entre ubicaciones
-- PostgreSQL / Supabase
-- =========================================================
-- Una relación indica que una ubicación ABASTECE a otra
-- ubicación o a una máquina. Sirve como guía para traslados
-- y reposiciones.
--
-- Relaciones permitidas:
--   Bodega -> Tienda
--   Bodega -> Máquina
--   Tienda -> Máquina
--   Tienda -> Tienda
--
-- La base de datos garantiza:
--   - el origen siempre es una ubicación (tabla tienda);
--   - el destino es una ubicación o una máquina, nunca ambos;
--   - una ubicación no se abastece a sí misma;
--   - no se repite la misma relación (se inactiva, no se borra).
--
-- La API valida además que el destino que es ubicación sea
-- de tipo TIENDA (no se permite Bodega como destino).
-- =========================================================

BEGIN;


-- =========================================================
-- 1. TIPO DE UBICACIÓN
-- =========================================================
-- Distingue tiendas de bodegas. Las ubicaciones existentes
-- (Ultrapark 1, Ultrapark 2 y UltraLag) quedan como TIENDA.
-- =========================================================

ALTER TABLE public.tienda
    ADD COLUMN IF NOT EXISTS tipo VARCHAR(20)
        NOT NULL DEFAULT 'TIENDA'
        CONSTRAINT chk_tienda_tipo
            CHECK (tipo IN ('TIENDA', 'BODEGA'));


-- =========================================================
-- 2. TABLA RELACION_ABASTECIMIENTO
-- =========================================================

CREATE TABLE IF NOT EXISTS public.relacion_abastecimiento (

    id_relacion BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Ubicación que abastece (Bodega o Tienda).
    id_tienda_origen BIGINT NOT NULL,

    -- Destino: una ubicación o una máquina (solo uno de los dos).
    id_tienda_destino BIGINT,
    id_maquina_destino BIGINT,

    estado BOOLEAN NOT NULL DEFAULT TRUE,

    observaciones VARCHAR(500),

    fecha_registro TIMESTAMPTZ
        NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_relacion_tienda_origen
        FOREIGN KEY (id_tienda_origen)
        REFERENCES public.tienda(id_tienda),

    CONSTRAINT fk_relacion_tienda_destino
        FOREIGN KEY (id_tienda_destino)
        REFERENCES public.tienda(id_tienda),

    CONSTRAINT fk_relacion_maquina_destino
        FOREIGN KEY (id_maquina_destino)
        REFERENCES public.maquina(id_maquina),

    CONSTRAINT chk_relacion_un_destino
        CHECK (
            (id_tienda_destino IS NOT NULL AND id_maquina_destino IS NULL)
            OR
            (id_tienda_destino IS NULL AND id_maquina_destino IS NOT NULL)
        ),

    CONSTRAINT chk_relacion_distinta
        CHECK (
            id_tienda_destino IS NULL
            OR id_tienda_destino <> id_tienda_origen
        )
);


-- No se repite la misma relación (origen -> destino).

CREATE UNIQUE INDEX IF NOT EXISTS uq_relacion_tienda_destino
ON public.relacion_abastecimiento(id_tienda_origen, id_tienda_destino)
WHERE id_tienda_destino IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_relacion_maquina_destino
ON public.relacion_abastecimiento(id_tienda_origen, id_maquina_destino)
WHERE id_maquina_destino IS NOT NULL;


-- Índices para consultar relaciones por destino.

CREATE INDEX IF NOT EXISTS idx_relacion_tienda_destino
ON public.relacion_abastecimiento(id_tienda_destino);

CREATE INDEX IF NOT EXISTS idx_relacion_maquina_destino
ON public.relacion_abastecimiento(id_maquina_destino);


-- =========================================================
-- 3. SEGURIDAD
-- =========================================================
-- Igual que el resto de las tablas: RLS activada. El acceso
-- se hace desde el backend PHP con el rol de la base.
-- =========================================================

ALTER TABLE public.relacion_abastecimiento
    ENABLE ROW LEVEL SECURITY;


COMMIT;
