-- =========================================================
-- VendingMiniMarket
-- MODULO 3: CATALOGO DE PRODUCTOS
-- PostgreSQL / Supabase
-- =========================================================


-- =========================================================
-- 1. CATEGORIA
-- =========================================================

CREATE TABLE IF NOT EXISTS public.categoria (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(250),
    estado BOOLEAN NOT NULL DEFAULT TRUE
);


-- =========================================================
-- 2. PROVEEDOR
-- =========================================================

CREATE TABLE IF NOT EXISTS public.proveedor (
    id_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    contacto VARCHAR(150),
    telefono VARCHAR(30),
    correo VARCHAR(150),
    direccion VARCHAR(250),
    estado BOOLEAN NOT NULL DEFAULT TRUE
);


-- =========================================================
-- 3. IMPUESTO
-- =========================================================

CREATE TABLE IF NOT EXISTS public.impuesto (
    id_impuesto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    porcentaje NUMERIC(5,2) NOT NULL,
    descripcion VARCHAR(250),
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT chk_impuesto_porcentaje
        CHECK (porcentaje >= 0 AND porcentaje <= 100)
);


-- =========================================================
-- 4. MARGEN_GANANCIA
-- =========================================================

CREATE TABLE IF NOT EXISTS public.margen_ganancia (
    id_margen BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    porcentaje NUMERIC(5,2) NOT NULL,
    descripcion VARCHAR(250),
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT chk_margen_porcentaje
        CHECK (porcentaje >= 0 AND porcentaje <= 100)
);


-- =========================================================
-- 5. PRODUCTO
-- =========================================================

CREATE TABLE IF NOT EXISTS public.producto (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_categoria BIGINT NOT NULL,
    id_proveedor BIGINT NOT NULL,
    id_impuesto BIGINT NOT NULL,

    codigo_articulo_retail VARCHAR(100) UNIQUE,
    codigo_barras VARCHAR(100) UNIQUE,

    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(300),

    estado BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_producto_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES public.categoria(id_categoria),

    CONSTRAINT fk_producto_proveedor
        FOREIGN KEY (id_proveedor)
        REFERENCES public.proveedor(id_proveedor),

    CONSTRAINT fk_producto_impuesto
        FOREIGN KEY (id_impuesto)
        REFERENCES public.impuesto(id_impuesto)
);


-- =========================================================
-- 6. PRECIO_TIENDA
-- =========================================================

CREATE TABLE IF NOT EXISTS public.precio_tienda (
    id_precio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_producto BIGINT NOT NULL,
    id_tienda BIGINT NOT NULL,
    id_margen BIGINT NOT NULL,

    costo NUMERIC(12,2) NOT NULL,
    precio_sin_impuesto NUMERIC(12,2) NOT NULL,
    precio_venta NUMERIC(12,2) NOT NULL,

    fecha_inicio TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_fin TIMESTAMPTZ,

    estado BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_precio_producto
        FOREIGN KEY (id_producto)
        REFERENCES public.producto(id_producto),

    CONSTRAINT fk_precio_tienda
        FOREIGN KEY (id_tienda)
        REFERENCES public.tienda(id_tienda),

    CONSTRAINT fk_precio_margen
        FOREIGN KEY (id_margen)
        REFERENCES public.margen_ganancia(id_margen),

    CONSTRAINT chk_precio_costo
        CHECK (costo >= 0),

    CONSTRAINT chk_precio_sin_impuesto
        CHECK (precio_sin_impuesto >= 0),

    CONSTRAINT chk_precio_venta
        CHECK (precio_venta >= 0)
);
-- =========================================================
-- MÓDULO 3 — CATÁLOGO DE PRODUCTOS
-- DATOS BASE
-- =========================================================


-- ---------------------------------------------------------
-- IMPUESTOS
-- ---------------------------------------------------------

INSERT INTO public.impuesto
(nombre, porcentaje, descripcion, estado)
VALUES
('IVA 13%', 13.00, 'Impuesto general aplicado al producto', TRUE)
ON CONFLICT (nombre) DO NOTHING;


-- ---------------------------------------------------------
-- MÁRGENES DE GANANCIA
-- ---------------------------------------------------------

INSERT INTO public.margen_ganancia
(nombre, porcentaje, descripcion, estado)
VALUES
('Margen 1.4', 40.00, 'Factor de precio 1.4', TRUE),
('Margen 1.5', 50.00, 'Factor de precio 1.5', TRUE),
('Margen 1.6', 60.00, 'Factor de precio 1.6', TRUE),
('Margen 1.7', 70.00, 'Factor de precio 1.7', TRUE)
ON CONFLICT (nombre) DO NOTHING;

-- ---------------------------------------------------------
-- CATEGORÍAS
-- ---------------------------------------------------------

INSERT INTO public.categoria
(nombre, descripcion, estado)
VALUES
('Bebidas', 'Productos de bebidas', TRUE),
('Confites y Chocolates', 'Confites, chocolates y productos relacionados', TRUE),
('Galletas', 'Productos de galletería', TRUE),
('Snacks', 'Snacks y productos similares', TRUE),
('Panadería', 'Productos de panadería', TRUE),
('Pastillas y Cuidado personal', 'Productos de farmacia y cuidado personal', TRUE),
('Helados', 'Helados y productos congelados relacionados', TRUE),
('Yogur y lácteos', 'Yogures y productos lácteos', TRUE),
('Comida preparada', 'Alimentos preparados', TRUE),
('Maní y frutos secos', 'Maní, semillas y frutos secos', TRUE),
('Item Hierarchy 1', 'Productos pendientes de asignar a una categoría definitiva', TRUE)
ON CONFLICT (nombre) DO NOTHING;

-- ---------------------------------------------------------
-- PROVEEDORES
-- ---------------------------------------------------------

INSERT INTO public.proveedor
(nombre, estado)
VALUES
('Dinant', TRUE),
('Florida', TRUE),
('Dimarpa', TRUE),
('Aguilar', TRUE),
('Dos Pinos', TRUE),
('Bimbo', TRUE),
('Salvador Ramirez', TRUE),
('Coarsa', TRUE),
('Diana', TRUE),
('Pozuelo', TRUE),
('Coca Cola', TRUE),
('Emsar Global', TRUE),
('Disal', TRUE),
('PriceSmart', TRUE),
('Jack', TRUE),
('Dipo', TRUE),
('Distribuidora J y J', TRUE),
('Preparatos', TRUE)
ON CONFLICT (nombre) DO NOTHING;

-- ---------------------------------------------------------
-- IMPUESTOS ADICIONALES
-- ---------------------------------------------------------

INSERT INTO public.impuesto
(nombre, porcentaje, descripcion, estado)
VALUES
('IVA 1%', 1.00, 'Impuesto del 1% aplicado según el producto', TRUE),
('IVA 2%', 2.00, 'Impuesto del 2% aplicado según el producto', TRUE)
ON CONFLICT (nombre) DO NOTHING;


SELECT
    'CATEGORIA' AS tipo,
    id_categoria AS id,
    nombre
FROM public.categoria

UNION ALL

SELECT
    'IMPUESTO' AS tipo,
    id_impuesto AS id,
    nombre
FROM public.impuesto

UNION ALL

SELECT
    'PROVEEDOR' AS tipo,
    id_proveedor AS id,
    nombre
FROM public.proveedor

ORDER BY tipo, id;

-- Verificar cantidad de productos importados
SELECT COUNT(*) AS total_productos
FROM public.producto;

-- Ajustar la secuencia del ID para que los próximos
-- productos continúen después del último ID importado
SELECT setval(
    pg_get_serial_sequence('public.producto', 'id_producto'),
    (SELECT MAX(id_producto) FROM public.producto),
    TRUE
);

-- =========================================================
-- MÁQUINAS
-- HU-17 - Administración de máquinas
-- =========================================================

BEGIN;


-- =========================================================
-- 1. TABLA MAQUINA
-- =========================================================
-- Cada máquina pertenece a una tienda.
-- El código de la máquina debe ser único.
-- Ejemplo:
-- VMM UL 001
-- VMM UP1 001
-- VMM UP2 003
-- =========================================================

CREATE TABLE IF NOT EXISTS public.maquina (

    id_maquina BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_tienda BIGINT NOT NULL,

    codigo VARCHAR(100) NOT NULL UNIQUE,

    nombre VARCHAR(150) NOT NULL,

    ubicacion VARCHAR(200),

    modelo VARCHAR(100),

    tipo VARCHAR(100),

    estado BOOLEAN NOT NULL DEFAULT TRUE,

    observaciones VARCHAR(500),

    fecha_registro TIMESTAMPTZ
        NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_maquina_tienda
        FOREIGN KEY (id_tienda)
        REFERENCES public.tienda(id_tienda)
);


-- Índice para buscar rápidamente las máquinas de una tienda.

CREATE INDEX IF NOT EXISTS idx_maquina_tienda
ON public.maquina(id_tienda);


-- =========================================================
-- 2. TABLA MAQUINA_PRODUCTO
-- =========================================================
-- Define qué producto está configurado en cada canal
-- de una máquina.
--
-- Ejemplo:
--
-- Máquina VMM UL 001
--
-- Canal 1 -> Coca Cola
-- Canal 2 -> Monster
-- Canal 3 -> Fanta
--
-- capacidad = cantidad máxima que soporta ese canal.
--
-- El stock actual NO se guarda aquí.
-- Eso se manejará luego en el módulo de inventario.
-- =========================================================

CREATE TABLE IF NOT EXISTS public.maquina_producto (

    id_maquina_producto BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_maquina BIGINT NOT NULL,

    id_producto BIGINT NOT NULL,

    canal VARCHAR(50) NOT NULL,

    capacidad INT,

    estado BOOLEAN NOT NULL DEFAULT TRUE,

    fecha_actualizacion TIMESTAMPTZ
        NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_maquina_producto_maquina
        FOREIGN KEY (id_maquina)
        REFERENCES public.maquina(id_maquina),

    CONSTRAINT fk_maquina_producto_producto
        FOREIGN KEY (id_producto)
        REFERENCES public.producto(id_producto),

    CONSTRAINT chk_maquina_producto_capacidad
        CHECK (
            capacidad IS NULL
            OR capacidad >= 0
        ),

    -- Una máquina no puede tener dos configuraciones
    -- diferentes para el mismo canal.

    CONSTRAINT uq_maquina_canal
        UNIQUE (id_maquina, canal)
);


-- Índices para búsquedas rápidas.

CREATE INDEX IF NOT EXISTS idx_maquina_producto_maquina
ON public.maquina_producto(id_maquina);

CREATE INDEX IF NOT EXISTS idx_maquina_producto_producto
ON public.maquina_producto(id_producto);


COMMIT;

SELECT table_name, ordinal_position AS n, column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name IN ('categoria','impuesto','proveedor','producto',
                     'producto_proveedor','precio_tienda','margen_ganancia','bitacora_auditoria')
ORDER BY table_name, ordinal_position;

SELECT c.relname AS tabla, k.conname, k.contype, pg_get_constraintdef(k.oid) AS definicion
FROM pg_constraint k
JOIN pg_class c ON c.oid = k.conrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'public'
  AND c.relname IN ('categoria','impuesto','proveedor','producto',
                    'producto_proveedor','precio_tienda','margen_ganancia','bitacora_auditoria')
  AND k.contype IN ('f','u','c')
ORDER BY c.relname, k.contype, k.conname;

SELECT 'categoria' AS tabla, to_jsonb(t) AS fila FROM (SELECT * FROM categoria LIMIT 3) t
UNION ALL SELECT 'impuesto', to_jsonb(t) FROM (SELECT * FROM impuesto LIMIT 3) t
UNION ALL SELECT 'proveedor', to_jsonb(t) FROM (SELECT * FROM proveedor LIMIT 2) t
UNION ALL SELECT 'producto_proveedor', to_jsonb(t) FROM (SELECT * FROM producto_proveedor LIMIT 2) t
UNION ALL SELECT 'margen_ganancia', to_jsonb(t) FROM (SELECT * FROM margen_ganancia LIMIT 4) t
UNION ALL SELECT 'producto', to_jsonb(t) FROM (SELECT * FROM producto LIMIT 3) t;