-- =========================================================
-- VendingMiniMarket
-- Módulo 1: Seguridad y acceso
-- PostgreSQL / Supabase
-- =========================================================


-- =========================================================
-- 1. ROL
-- =========================================================

CREATE TABLE IF NOT EXISTS public.rol (
    id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(200),
    estado BOOLEAN NOT NULL DEFAULT TRUE
);


-- =========================================================
-- 2. TIENDA
-- Dependencia necesaria para USUARIO_TIENDA
-- La lógica completa se trabajará en su módulo.
-- =========================================================

CREATE TABLE IF NOT EXISTS public.tienda (
    id_tienda BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    ubicacion VARCHAR(200),
    estado BOOLEAN NOT NULL DEFAULT TRUE
);


-- =========================================================
-- 3. USUARIO
-- =========================================================

CREATE TABLE IF NOT EXISTS public.usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol BIGINT NOT NULL,

    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100),
    correo VARCHAR(150) NOT NULL UNIQUE,

    password_hash TEXT NOT NULL,

    estado BOOLEAN NOT NULL DEFAULT TRUE,
    ultimo_acceso TIMESTAMPTZ,

    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (id_rol)
        REFERENCES public.rol(id_rol)
);


-- =========================================================
-- 4. USUARIO_TIENDA
-- =========================================================

CREATE TABLE IF NOT EXISTS public.usuario_tienda (
    id_usuario_tienda BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_usuario BIGINT NOT NULL,
    id_tienda BIGINT NOT NULL,

    estado BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_usuario_tienda_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES public.usuario(id_usuario),

    CONSTRAINT fk_usuario_tienda_tienda
        FOREIGN KEY (id_tienda)
        REFERENCES public.tienda(id_tienda),

    CONSTRAINT uq_usuario_tienda
        UNIQUE (id_usuario, id_tienda)
);


-- =========================================================
-- 5. BITACORA_AUDITORIA
-- =========================================================

CREATE TABLE IF NOT EXISTS public.bitacora_auditoria (
    id_evento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_usuario BIGINT,
    id_tienda BIGINT,

    entidad VARCHAR(100) NOT NULL,
    accion VARCHAR(100) NOT NULL,

    valor_anterior JSONB,
    valor_nuevo JSONB,

    resultado VARCHAR(50),
    ip_origen INET,

    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_bitacora_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES public.usuario(id_usuario),

    CONSTRAINT fk_bitacora_tienda
        FOREIGN KEY (id_tienda)
        REFERENCES public.tienda(id_tienda)
);